# Generated by Django 5.2.6 on 2025-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aboutus2_title', models.CharField(max_length=150)),
                ('Aboutus2_desc', models.TextField()),
                ('Aboutus2_read_link', models.CharField(max_length=150)),
                ('Aboutus2_img', models.FileField(default=None, max_length=250, null=True, upload_to='aboutus2')),
            ],
        ),
    ]
