# Generated by Django 5.2.6 on 2025-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='no_of_guests',
            field=models.IntegerField(),
        ),
    ]
