# Generated by Django 5.2.6 on 2025-10-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_no_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='no_of_guests',
            field=models.CharField(max_length=20),
        ),
    ]
