# Generated by Django 5.2.6 on 2025-10-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='no_of_guests',
            field=models.IntegerField(max_length=5),
        ),
    ]
