# Generated by Django 5.2.6 on 2025-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_no_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='no_of_guests',
            field=models.IntegerField(max_length=2),
        ),
    ]
