# Generated by Django 5.2.6 on 2025-10-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aboutus_title', models.CharField(max_length=150)),
                ('Aboutus_desc', models.TextField()),
                ('Aboutus_read_link', models.CharField(max_length=150)),
            ],
        ),
    ]
