# Generated by Django 5.2.6 on 2025-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Aboutus_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='aboutus'),
        ),
    ]
