# Generated by Django 5.2.6 on 2025-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourguards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ourguards_person', models.CharField(max_length=250)),
                ('Ourguards_post', models.CharField(max_length=250)),
                ('Ourguards_img', models.FileField(default=None, max_length=250, null=True, upload_to='ourguards')),
            ],
        ),
    ]
