# Generated by Django 5.2.6 on 2025-10-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourguardsnew', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourguards',
            old_name='Ourguards_person',
            new_name='Ourguards_placename',
        ),
    ]
